package com.leader.api.service.org.authorization;

public enum OrgAuthority {
    ADMIN_FUNCTIONS,
    ANNOUNCEMENT_MANAGEMENT,
    ATTENDANCE,
    RECRUIT,
    RECRUIT_SETTING,
    BULLETIN_MANAGEMENT,
    TIMELINE_MANAGEMENT,
    TASK,
    STRUCTURE_MANAGEMENT,
    PUBLIC_INFO_MANAGEMENT,
    PRESIDENT_TRANSFER,
    BASIC
}
