# This workflow will build a Java project with Maven when pushed to dev

name: Maven Dev Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "dev"
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package
    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.P_HOST }}
        user: ${{ secrets.P_USER }}
        pass: ${{ secrets.P_PASS }}
        connect_timeout: 10s
        first_ssh: |
          cd ${{ secrets.P_PATH }}
          tmux kill-session -t ${{ secrets.P_SESSION }}
          rm ${{ secrets.P_JAR }}
        scp: |
          "./target/${{ secrets.P_JAR }}" => ${{ secrets.P_PATH }}
        last_ssh: |
          sleep 10
          cd ${{ secrets.P_PATH }}
          tmux new -d -s ${{ secrets.P_SESSION }} "java -jar ${{ secrets.P_JAR }}"
